# Generated by Django 3.0.8 on 2020-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20201104_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_no', models.IntegerField()),
                ('author', models.CharField(max_length=40)),
                ('department', models.CharField(choices=[('ece', 'ece'), ('cse', 'cse'), ('it', 'it'), ('civil', 'civil'), ('mech', 'mech'), ('chem', 'chem'), ('mme', 'mme')], max_length=10)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
